### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by stevemar** [IBM/xgboost-smote-detect-fraud#1]
I went through this code pattern, here are my thoughts:

1. Please make sure someone from the SI team runs through this, as a quick validation that it's easy to follow.

2. State early on where the data came from. It's in the `data` folder, but has no attribution. In the README please state the website where it's from and properly attribute the data set.

3. (nit pick) Add spaces before braces "one(False Negatives)" should be "one (False Negatives)"

4. Remove Steps 1 and 2 (sign ups)

5. Step 3 -- I updated one of our notebook repos: https://github.com/IBM/kafka-streaming-click-analysis#run-using-a-jupyter-notebook-in-the-ibm-watson-studio -- please use this as a template as it includes updated screenshots -- do not include the spark step

6. The `Analyze the results` section is a little boring. Can you add to it? (I realize this is very subjective)

**Comment by RK-Sharath** [comment]
@stevemart Thanks for your time and feedback. I have updated the documentation. Please review.

**Comment by stevemar** [comment]
@RK-Sharath please use pull requests when closing bugs (or always).

**Comment by RK-Sharath** [comment]
@stevemart I will do it. Sorry about that.

**Comment by stevemar** [comment]
@RK-Sharath i opened #2, i saw a bit more detail in the kaggle link. This otherwise looks fine to me. I strongly recommend getting someone else on your team to run through it and give you feedback, i haven't gone through the pattern itself.

**Comment by RK-Sharath** [comment]
@stevemart I have addressed #2 and submitted a PR. I have reviewed the pattern multiple times and tested the functionality. Please advise whether it needs another validation.

**Comment by RK-Sharath** [comment]
@stevemart Suggested changes are complete.
